// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'Utils.dart';
import 'utils/ImageManager.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5612710838682895620),
      name: 'GenerationParams',
      lastPropertyId: const obx_int.IdUid(23, 664446500433716605),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8369849383162291980),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3039778777548549755),
            name: 'positive',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 157377979103234256),
            name: 'negative',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3742085914055716074),
            name: 'steps',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4046093489433718740),
            name: 'sampler',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1359481478935137190),
            name: 'cfgScale',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1685994634248954341),
            name: 'seed',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 627957826146350439),
            name: 'checkpoint',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6351934713857678324),
            name: 'checkpointHash',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4172788466155878684),
            name: 'vae',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2749991649759715806),
            name: 'vaeHash',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 3563895506397998225),
            name: 'denoisingStrength',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 5697736120636264323),
            name: 'rng',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 2895843173158216800),
            name: 'hiresSampler',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 3285834822174973631),
            name: 'hiresUpscaler',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 3808804731464400975),
            name: 'hiresUpscale',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 3137415165080915469),
            name: 'version',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 7463245307920649530),
            name: 'rawData',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 3859175668864835803),
            name: 'dbSize',
            type: 27,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 7409481922305154350),
            name: 'dbCheckpointType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 1947406572180551226),
            name: 'dbTiHashes',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 34057710725419835),
            name: 'dbRating',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 664446500433716605),
            name: 'dbParams',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 836234286331607557),
      name: 'ImageMeta',
      lastPropertyId: const obx_int.IdUid(24, 2932544344916973882),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1703735352965974354),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7713961108608267264),
            name: 'keyup',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 6752289052878076801)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2625735042295448668),
            name: 'host',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5737418068083552570),
            name: 'mine',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8983515968784810856),
            name: 'fileTypeExtension',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 961594898156003123),
            name: 'dateModified',
            type: 10,
            flags: 8,
            indexId: const obx_int.IdUid(3, 1115789481604348470)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4322825290257132049),
            name: 'fileSize',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3222248826317769125),
            name: 'fileName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6624945592181831535),
            name: 'pathHash',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 815588344921961931),
            name: 'fullPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 279678329775887907),
            name: 'fullNetworkPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 2047534565465207797),
            name: 'tempFilePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 4085219615235809694),
            name: 'dbGenerationParamsId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 5018930150217760427),
            relationTarget: 'GenerationParams'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 4079921586496920314),
            name: 'networkThumbnail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 1036681876303578439),
            name: 'dbRe',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 5306408746474920228),
            name: 'dbSize',
            type: 27,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 42329194016196444),
            name: 'dbOther',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 4341179877783419030),
            name: 'dbSpecific',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 2330948256636127591),
            name: 'dbThumbnail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 5447509339082301620),
            name: 'cacheFilePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 898841031516601779),
            name: 'fullImage',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(24, 2932544344916973882),
            name: 'dayKey',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(4, 1759563950951639925))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 836234286331607557),
      lastIndexId: const obx_int.IdUid(4, 1759563950951639925),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [7004923476242970745, 5867880175516831650],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    GenerationParams: obx_int.EntityDefinition<GenerationParams>(
        model: _entities[0],
        toOneRelations: (GenerationParams object) => [],
        toManyRelations: (GenerationParams object) => {},
        getId: (GenerationParams object) => object.id,
        setId: (GenerationParams object, int id) {
          object.id = id;
        },
        objectToFB: (GenerationParams object, fb.Builder fbb) {
          final positiveOffset = object.positive == null
              ? null
              : fbb.writeString(object.positive!);
          final negativeOffset = object.negative == null
              ? null
              : fbb.writeString(object.negative!);
          final samplerOffset =
              object.sampler == null ? null : fbb.writeString(object.sampler!);
          final checkpointOffset = object.checkpoint == null
              ? null
              : fbb.writeString(object.checkpoint!);
          final checkpointHashOffset = object.checkpointHash == null
              ? null
              : fbb.writeString(object.checkpointHash!);
          final vaeOffset =
              object.vae == null ? null : fbb.writeString(object.vae!);
          final vaeHashOffset =
              object.vaeHash == null ? null : fbb.writeString(object.vaeHash!);
          final rngOffset =
              object.rng == null ? null : fbb.writeString(object.rng!);
          final hiresSamplerOffset = object.hiresSampler == null
              ? null
              : fbb.writeString(object.hiresSampler!);
          final hiresUpscalerOffset = object.hiresUpscaler == null
              ? null
              : fbb.writeString(object.hiresUpscaler!);
          final versionOffset =
              object.version == null ? null : fbb.writeString(object.version!);
          final rawDataOffset =
              object.rawData == null ? null : fbb.writeString(object.rawData!);
          final dbSizeOffset =
              object.dbSize == null ? null : fbb.writeListInt64(object.dbSize!);
          final dbTiHashesOffset = fbb.writeString(object.dbTiHashes);
          final dbParamsOffset = fbb.writeString(object.dbParams);
          fbb.startTable(24);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, positiveOffset);
          fbb.addOffset(2, negativeOffset);
          fbb.addInt64(3, object.steps);
          fbb.addOffset(4, samplerOffset);
          fbb.addFloat64(5, object.cfgScale);
          fbb.addInt64(6, object.seed);
          fbb.addOffset(7, checkpointOffset);
          fbb.addOffset(8, checkpointHashOffset);
          fbb.addOffset(9, vaeOffset);
          fbb.addOffset(10, vaeHashOffset);
          fbb.addFloat64(11, object.denoisingStrength);
          fbb.addOffset(12, rngOffset);
          fbb.addOffset(13, hiresSamplerOffset);
          fbb.addOffset(14, hiresUpscalerOffset);
          fbb.addFloat64(15, object.hiresUpscale);
          fbb.addOffset(16, versionOffset);
          fbb.addOffset(17, rawDataOffset);
          fbb.addOffset(18, dbSizeOffset);
          fbb.addInt64(19, object.dbCheckpointType);
          fbb.addOffset(20, dbTiHashesOffset);
          fbb.addInt64(21, object.dbRating);
          fbb.addOffset(22, dbParamsOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final positiveParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final negativeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final stepsParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final samplerParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final cfgScaleParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 14);
          final seedParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final checkpointParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final checkpointHashParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final vaeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final vaeHashParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);
          final denoisingStrengthParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 26);
          final rngParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 28);
          final hiresSamplerParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 30);
          final hiresUpscalerParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 32);
          final hiresUpscaleParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 34);
          final versionParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 36);
          final rawDataParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 38);
          final object = GenerationParams(
              id: idParam,
              positive: positiveParam,
              negative: negativeParam,
              steps: stepsParam,
              sampler: samplerParam,
              cfgScale: cfgScaleParam,
              seed: seedParam,
              checkpoint: checkpointParam,
              checkpointHash: checkpointHashParam,
              vae: vaeParam,
              vaeHash: vaeHashParam,
              denoisingStrength: denoisingStrengthParam,
              rng: rngParam,
              hiresSampler: hiresSamplerParam,
              hiresUpscaler: hiresUpscalerParam,
              hiresUpscale: hiresUpscaleParam,
              version: versionParam,
              rawData: rawDataParam)
            ..dbSize = const fb.ListReader<int>(fb.Int64Reader(), lazy: false)
                .vTableGetNullable(buffer, rootOffset, 40)
            ..dbCheckpointType =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 42, 0)
            ..dbTiHashes = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 44, '')
            ..dbRating =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 46, 0)
            ..dbParams = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 48, '');

          return object;
        }),
    ImageMeta: obx_int.EntityDefinition<ImageMeta>(
        model: _entities[1],
        toOneRelations: (ImageMeta object) => [object.dbGenerationParams],
        toManyRelations: (ImageMeta object) => {},
        getId: (ImageMeta object) => object.id,
        setId: (ImageMeta object, int id) {
          object.id = id;
        },
        objectToFB: (ImageMeta object, fb.Builder fbb) {
          final keyupOffset = fbb.writeString(object.keyup);
          final hostOffset =
              object.host == null ? null : fbb.writeString(object.host!);
          final mineOffset =
              object.mine == null ? null : fbb.writeString(object.mine!);
          final fileTypeExtensionOffset =
              fbb.writeString(object.fileTypeExtension);
          final fileNameOffset = fbb.writeString(object.fileName);
          final pathHashOffset = fbb.writeString(object.pathHash);
          final fullPathOffset = object.fullPath == null
              ? null
              : fbb.writeString(object.fullPath!);
          final fullNetworkPathOffset = object.fullNetworkPath == null
              ? null
              : fbb.writeString(object.fullNetworkPath!);
          final tempFilePathOffset = object.tempFilePath == null
              ? null
              : fbb.writeString(object.tempFilePath!);
          final networkThumbnailOffset = object.networkThumbnail == null
              ? null
              : fbb.writeString(object.networkThumbnail!);
          final dbSizeOffset =
              object.dbSize == null ? null : fbb.writeListInt64(object.dbSize!);
          final dbOtherOffset = fbb.writeString(object.dbOther);
          final dbSpecificOffset = fbb.writeString(object.dbSpecific);
          final dbThumbnailOffset = object.dbThumbnail == null
              ? null
              : fbb.writeString(object.dbThumbnail!);
          final cacheFilePathOffset = object.cacheFilePath == null
              ? null
              : fbb.writeString(object.cacheFilePath!);
          final fullImageOffset = object.fullImage == null
              ? null
              : fbb.writeListInt8(object.fullImage!);
          fbb.startTable(25);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, keyupOffset);
          fbb.addOffset(2, hostOffset);
          fbb.addOffset(3, mineOffset);
          fbb.addOffset(4, fileTypeExtensionOffset);
          fbb.addInt64(5, object.dateModified?.millisecondsSinceEpoch);
          fbb.addInt64(6, object.fileSize);
          fbb.addOffset(7, fileNameOffset);
          fbb.addOffset(8, pathHashOffset);
          fbb.addOffset(9, fullPathOffset);
          fbb.addOffset(10, fullNetworkPathOffset);
          fbb.addOffset(11, tempFilePathOffset);
          fbb.addInt64(12, object.dbGenerationParams.targetId);
          fbb.addOffset(15, networkThumbnailOffset);
          fbb.addInt64(16, object.dbRe);
          fbb.addOffset(17, dbSizeOffset);
          fbb.addOffset(18, dbOtherOffset);
          fbb.addOffset(19, dbSpecificOffset);
          fbb.addOffset(20, dbThumbnailOffset);
          fbb.addOffset(21, cacheFilePathOffset);
          fbb.addOffset(22, fullImageOffset);
          fbb.addInt64(23, object.dayKey);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateModifiedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final hostParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final mineParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final fileTypeExtensionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final fileSizeParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final dateModifiedParam = dateModifiedValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dateModifiedValue);
          final fullPathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final fullNetworkPathParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24);
          final fullImageParam = const fb.Uint8ListReader(lazy: false)
              .vTableGetNullable(buffer, rootOffset, 48) as Uint8List?;
          final networkThumbnailParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 34);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = ImageMeta(
              host: hostParam,
              mine: mineParam,
              fileTypeExtension: fileTypeExtensionParam,
              fileSize: fileSizeParam,
              dateModified: dateModifiedParam,
              fullPath: fullPathParam,
              fullNetworkPath: fullNetworkPathParam,
              fullImage: fullImageParam,
              networkThumbnail: networkThumbnailParam,
              id: idParam)
            ..keyup = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..fileName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '')
            ..pathHash = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 20, '')
            ..tempFilePath = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 26)
            ..dbRe = const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0)
            ..dbSize = const fb.ListReader<int>(fb.Int64Reader(), lazy: false)
                .vTableGetNullable(buffer, rootOffset, 38)
            ..dbOther = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 40, '')
            ..dbSpecific = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 42, '')
            ..dbThumbnail = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 44)
            ..cacheFilePath = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 46)
            ..dayKey =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 50, 0);
          object.dbGenerationParams.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          object.dbGenerationParams.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [GenerationParams] entity fields to define ObjectBox queries.
class GenerationParams_ {
  /// See [GenerationParams.id].
  static final id =
      obx.QueryIntegerProperty<GenerationParams>(_entities[0].properties[0]);

  /// See [GenerationParams.positive].
  static final positive =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[1]);

  /// See [GenerationParams.negative].
  static final negative =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[2]);

  /// See [GenerationParams.steps].
  static final steps =
      obx.QueryIntegerProperty<GenerationParams>(_entities[0].properties[3]);

  /// See [GenerationParams.sampler].
  static final sampler =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[4]);

  /// See [GenerationParams.cfgScale].
  static final cfgScale =
      obx.QueryDoubleProperty<GenerationParams>(_entities[0].properties[5]);

  /// See [GenerationParams.seed].
  static final seed =
      obx.QueryIntegerProperty<GenerationParams>(_entities[0].properties[6]);

  /// See [GenerationParams.checkpoint].
  static final checkpoint =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[7]);

  /// See [GenerationParams.checkpointHash].
  static final checkpointHash =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[8]);

  /// See [GenerationParams.vae].
  static final vae =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[9]);

  /// See [GenerationParams.vaeHash].
  static final vaeHash =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[10]);

  /// See [GenerationParams.denoisingStrength].
  static final denoisingStrength =
      obx.QueryDoubleProperty<GenerationParams>(_entities[0].properties[11]);

  /// See [GenerationParams.rng].
  static final rng =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[12]);

  /// See [GenerationParams.hiresSampler].
  static final hiresSampler =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[13]);

  /// See [GenerationParams.hiresUpscaler].
  static final hiresUpscaler =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[14]);

  /// See [GenerationParams.hiresUpscale].
  static final hiresUpscale =
      obx.QueryDoubleProperty<GenerationParams>(_entities[0].properties[15]);

  /// See [GenerationParams.version].
  static final version =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[16]);

  /// See [GenerationParams.rawData].
  static final rawData =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[17]);

  /// See [GenerationParams.dbSize].
  static final dbSize = obx.QueryIntegerVectorProperty<GenerationParams>(
      _entities[0].properties[18]);

  /// See [GenerationParams.dbCheckpointType].
  static final dbCheckpointType =
      obx.QueryIntegerProperty<GenerationParams>(_entities[0].properties[19]);

  /// See [GenerationParams.dbTiHashes].
  static final dbTiHashes =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[20]);

  /// See [GenerationParams.dbRating].
  static final dbRating =
      obx.QueryIntegerProperty<GenerationParams>(_entities[0].properties[21]);

  /// See [GenerationParams.dbParams].
  static final dbParams =
      obx.QueryStringProperty<GenerationParams>(_entities[0].properties[22]);
}

/// [ImageMeta] entity fields to define ObjectBox queries.
class ImageMeta_ {
  /// See [ImageMeta.id].
  static final id =
      obx.QueryIntegerProperty<ImageMeta>(_entities[1].properties[0]);

  /// See [ImageMeta.keyup].
  static final keyup =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[1]);

  /// See [ImageMeta.host].
  static final host =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[2]);

  /// See [ImageMeta.mine].
  static final mine =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[3]);

  /// See [ImageMeta.fileTypeExtension].
  static final fileTypeExtension =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[4]);

  /// See [ImageMeta.dateModified].
  static final dateModified =
      obx.QueryDateProperty<ImageMeta>(_entities[1].properties[5]);

  /// See [ImageMeta.fileSize].
  static final fileSize =
      obx.QueryIntegerProperty<ImageMeta>(_entities[1].properties[6]);

  /// See [ImageMeta.fileName].
  static final fileName =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[7]);

  /// See [ImageMeta.pathHash].
  static final pathHash =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[8]);

  /// See [ImageMeta.fullPath].
  static final fullPath =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[9]);

  /// See [ImageMeta.fullNetworkPath].
  static final fullNetworkPath =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[10]);

  /// See [ImageMeta.tempFilePath].
  static final tempFilePath =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[11]);

  /// See [ImageMeta.dbGenerationParams].
  static final dbGenerationParams =
      obx.QueryRelationToOne<ImageMeta, GenerationParams>(
          _entities[1].properties[12]);

  /// See [ImageMeta.networkThumbnail].
  static final networkThumbnail =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[13]);

  /// See [ImageMeta.dbRe].
  static final dbRe =
      obx.QueryIntegerProperty<ImageMeta>(_entities[1].properties[14]);

  /// See [ImageMeta.dbSize].
  static final dbSize =
      obx.QueryIntegerVectorProperty<ImageMeta>(_entities[1].properties[15]);

  /// See [ImageMeta.dbOther].
  static final dbOther =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[16]);

  /// See [ImageMeta.dbSpecific].
  static final dbSpecific =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[17]);

  /// See [ImageMeta.dbThumbnail].
  static final dbThumbnail =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[18]);

  /// See [ImageMeta.cacheFilePath].
  static final cacheFilePath =
      obx.QueryStringProperty<ImageMeta>(_entities[1].properties[19]);

  /// See [ImageMeta.fullImage].
  static final fullImage =
      obx.QueryByteVectorProperty<ImageMeta>(_entities[1].properties[20]);

  /// See [ImageMeta.dayKey].
  static final dayKey =
      obx.QueryIntegerProperty<ImageMeta>(_entities[1].properties[21]);
}
